export const arr=[
    {
      name:"Service1",
      cluster:"Preprod10",
      running:"healthy"
    },
    {
      name:"Service2",
      cluster:"Preprod10",
      running:"healthy"
    },
    {
      name:"Service3",
      cluster:"Preprod10",
      running:"unhealthy"
    },
    {
      name:"Service4",
      cluster:"Preprod11",
      running:"healthy"
    },
    {
      name:"Service5",
      cluster:"Preprod11",
      running:"unhealthy"
    },
    {
      name:"Service6",
      cluster:"Preprod11",
      running:"healthy"
    },
    {
      name:"Service7",
      cluster:"Preprod18",
      running:"unhealthy"
    },
    {
      name:"Service8",
      cluster:"Preprod18",
      running:"unhealthy"
    },
    {
      name:"Service9",
      cluster:"Preprod18",
      running:"healthy"
    }
  ]